# Texture and image formats
from OpenGL.GL import \
    GL_RGB, GL_RGB8, GL_RGBA, GL_RGBA8, \
    GL_RGB16F, GL_RGB32F, GL_RGBA16F, GL_RGBA32F, \
    GL_DEPTH24_STENCIL8, GL_DEPTH_STENCIL, GL_UNSIGNED_INT_24_8, \
    GL_R32I, GL_UNSIGNED_BYTE, GL_RED_INTEGER, \
    GL_REPEAT, GL_CLAMP_TO_EDGE, \
    GL_NEAREST, GL_LINEAR

class PIConstants:
    @staticmethod
    def ToOpenGLConstant(constant: int) -> int: return constant

    RGB, RGBA = GL_RGB, GL_RGBA
    RGB8, RGBA8, RGB16F, RGB32F, RGBA16F, RGBA32F = \
        GL_RGB8, GL_RGBA8, GL_RGB16F, GL_RGB32F, GL_RGBA16F, GL_RGBA32F
    
    DEPTH24_STENCIL8, DEPTH_STENCIL, UNSIGNED_INT_24_8, RED_INTEGER = \
        GL_DEPTH24_STENCIL8, GL_DEPTH_STENCIL, GL_UNSIGNED_INT_24_8, GL_RED_INTEGER

    R32I, UNSIGNED_BYTE = GL_R32I, GL_UNSIGNED_BYTE

    REPEAT, CLAMP_TO_EDGE  = GL_REPEAT, GL_CLAMP_TO_EDGE
    NEAREST, LINEAR        = GL_NEAREST, GL_LINEAR
